# Generated by Django 2.0 on 2018-05-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
